### ISSUE TITLE
i have mac

### ISSUE THREAD

**Issue by MHM5000** [wmchen/mlcbase#3]
hi
i randomly saw your package in pypi. you said, you don't have mac. 
i have. m2.
what do you need me to test?

**Comment by wmchen** [comment]
> hi i randomly saw your package in pypi. you said, you don't have mac. i have. m2. what do you need me to test?

Hello, much appreciate for your kind help!

For testing, the following steps may offer you a rough reference:
1. Clone this repository to your MAC device
2. Create a conda environment and run `pip install -r requirements.txt`
3. Fill the remote configurations in `tutorial_database.ipynb`, `tutorial_email.ipynb` and `tutorial_remote_connection.ipynb`
4. Run all the `.ipynb` files under the `tutorial` directory
5. Repeat the above step 2-4 on Python 3.6-3.13

Please record all errors during your testing process. You can directly capture screenshots and attach the corresponding Python version, and email me in one PDF file.

Besides, you can also fork this repository and help me fix the bugs you find during the tesing.

THANKS again for your kind help! Looking forward to your furter work.

Best Regards!

**Comment by MHM5000** [comment]
i'm happy to help, but that's a lot of work.
it would help if you had tests for your package and added tox to automate everything.
i have mariadb installed. it failed in table creation.
didn't test ssh and smtp, but the rest went through with py3.11

**Comment by wmchen** [comment]
> i'm happy to help, but that's a lot of work. it would help if you had tests for your package and added tox to automate everything. i have mariadb installed. it failed in table creation. didn't test ssh and smtp, but the rest went through with py3.11

I got it! Much appreciate for your contribution!

**Comment by wmchen** [comment]
@all-contributors please add @MHM5000 for test

**Comment by MHM5000** [comment]
nice bot.
ping me if tests were ready with dummy ssh/smtp also sqlite preconfigured...
